### ISSUE TITLE
Why int8 mode performance better?

### ISSUE THREAD

**Issue by zhangjinsong3** [lewes6369/TensorRT-Yolov3#22]
Thanks a lot for your amazing work. But a question is that why it performance even better for 5 mAP after speed up with int8 mode? That is really strange！

**Comment by lewes6369** [comment]
Usually Int8 mode gets a little worse infer result in the dataset. As I test other model tried int8 and fp32, the int8 mode gets a little worse but sometimes better result. So It is not certainly in all the model and all the test data. Maybe it is a method for preventing model overfitting so that gets a better result. By the way, I am not sure actually :)
